#!/bin/sh
COMMAND=$1
SQL_FILE1="tmp/cagong_area_202406061711.sql"
SQL_FILE2="tmp/cagong_cafe_202406061711.sql"

case $COMMAND in
  makemigrations)
    docker-compose exec django python manage.py makemigrations
    ;;
  migrate)
    docker-compose exec django python manage.py migrate
    ;;
  shell)
    docker-compose exec django python manage.py shell
    ;;
  load-dataset)
    docker exec -it django python manage.py crawlareas
    docker exec -it django python manage.py crawlcafes
    ;;
  *)
    echo "Usage: $0 {migrate|makemigrations|shell|load-dataset}"
    exit 1
    ;;
esac