#!/bin/sh
COMMAND=$1
SQL_FILE1="tmp/cagong_area_202406061711.sql"
SQL_FILE2="tmp/cagong_cafe_202406061711.sql"

case $COMMAND in
  makemigrations)
    docker-compose exec django python manage.py makemigrations
    ;;
  migrate)
    docker-compose exec django python manage.py migrate
    ;;
  shell)
    docker-compose exec django python manage.py shell
    ;;
  load-dataset)
    docker cp $SQL_FILE1 postgres:/$SQL_FILE1
    docker cp $SQL_FILE2 postgres:/$SQL_FILE2
    docker-compose exec postgres sh -c "PGPASSWORD='$POSTGRES_PASSWORD' psql -U $POSTGRES_USER -d $POSTGRES_DB -f $SQL_FILE1"
    docker-compose exec postgres sh -c "PGPASSWORD='$POSTGRES_PASSWORD' psql -U $POSTGRES_USER -d $POSTGRES_DB -f $SQL_FILE2"
    docker-compose exec postgres sh -c "rm $SQL_FILE1 $SQL_FILE2"
    ;;
  *)
    echo "Usage: $0 {migrate|makemigrations|shell|load-dataset}"
    exit 1
    ;;
esac