# Generated by Django 4.2.11 on 2024-05-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="wordcloud_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
