# Generated by Django 4.2.11 on 2024-06-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city_code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='county_code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='town_code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['city_code'], name='cagong_area_city_co_4642d0_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['county_code'], name='cagong_area_county__e1c30a_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['town_code'], name='cagong_area_town_co_615eef_idx'),
        ),
    ]
