# Generated by Django 4.2.11 on 2024-06-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0003_region_created_at_region_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='crawl_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
