# Generated by Django 4.2.11 on 2024-06-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0004_cafe_crawl_id_alter_cafe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_crawled',
            field=models.BooleanField(default=False),
        ),
    ]
