# Generated by Django 4.2.11 on 2024-06-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0005_cafe_is_crawled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='wordcloud_data',
            new_name='wordcloud',
        ),
    ]
