# Generated by Django 4.2.11 on 2024-06-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0006_rename_wordcloud_data_cafe_wordcloud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={},
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
