# Generated by Django 4.2.11 on 2024-06-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0007_alter_cafe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='address',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='phonenum',
            new_name='phone',
        ),
    ]
