# Generated by Django 4.2.11 on 2024-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0008_rename_address_cafe_addr_rename_latitude_cafe_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
