# Generated by Django 4.2.11 on 2024-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0009_alter_cafe_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='crawl_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
