# Generated by Django 4.2.11 on 2024-06-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0010_alter_cafe_crawl_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Area',
        ),
    ]
