# Generated by Django 4.2.11 on 2024-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagong', '0011_rename_region_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
