# Generated by Django 4.2.11 on 2024-06-02 02:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cagong", "0012_alter_cafe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="area",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cafe",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="review",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=datetime.datetime(2024, 6, 2, 2, 43, 16, 76820)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cafe",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=datetime.datetime(2024, 6, 2, 2, 43, 19, 191892)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
